// 常见开发工具的中文一句话简介（开箱即用，不联网）。
// key：工具名小写；Homebrew 第三方 tap 取最后一段，版本后缀（node@22、mysql@8.0）去掉后匹配。
// 只收录确定的说明，拿不准的不写——宁可回退到官方英文简介，也不要给错误描述。

export const DICT_ZH: Record<string, string> = {
  // ---------- 版本控制 / GitHub ----------
  git: '分布式版本控制系统',
  gh: 'GitHub 官方命令行工具',
  'git-delta': 'git diff 的语法高亮分页器',
  'git-filter-repo': '重写 git 历史（批量删文件、改作者等）',
  'git-lfs': 'Git 大文件存储扩展',
  lazygit: '终端里的 git 图形化界面',
  tig: '终端里的 git 浏览器',
  'pre-commit': '管理 git 提交前钩子的框架',
  glab: 'GitLab 官方命令行工具',

  // ---------- 语言运行时与版本管理 ----------
  node: 'Node.js JavaScript 运行时',
  python: 'Python 解释器',
  'python@3': 'Python 解释器',
  go: 'Go 语言编译器与工具链',
  rust: 'Rust 语言编译器与工具链',
  rustup: 'Rust 工具链版本管理器',
  ruby: 'Ruby 解释器',
  php: 'PHP 解释器',
  composer: 'PHP 依赖管理器',
  openjdk: 'Java 开发工具包（OpenJDK）',
  temurin: 'Eclipse Temurin Java 开发工具包',
  kotlin: 'Kotlin 语言编译器',
  deno: 'JavaScript / TypeScript 运行时（Deno）',
  bun: 'JavaScript 运行时、打包器与包管理器（Bun）',
  fnm: '快速的 Node.js 版本管理器',
  nvm: 'Node.js 版本管理器',
  volta: 'JavaScript 工具链版本管理器',
  pyenv: 'Python 版本管理器',
  rbenv: 'Ruby 版本管理器',
  asdf: '多语言运行时版本管理器',
  mise: '多语言运行时与环境变量管理器',
  uv: '极快的 Python 包与项目管理器',
  pipx: '把 Python 命令行工具装进独立环境',
  poetry: 'Python 依赖管理与打包工具',

  // ---------- 包管理器 ----------
  npm: 'Node.js 官方包管理器',
  yarn: 'JavaScript 包管理器（Yarn）',
  pnpm: '节省磁盘的 JavaScript 包管理器',
  corepack: 'Node.js 自带的包管理器版本管理',
  cocoapods: 'iOS / macOS 项目的依赖管理器',
  carthage: 'iOS / macOS 去中心化依赖管理器',
  mas: '命令行操作 Mac App Store',
  gradle: 'Java / Android 构建工具',
  maven: 'Java 项目构建与依赖管理工具',
  cmake: '跨平台 C/C++ 构建系统生成器',
  ninja: '专注速度的小型构建系统',
  make: '经典的构建自动化工具',

  // ---------- 容器与云 ----------
  docker: '容器引擎命令行',
  'docker-compose': '用 YAML 编排多个 Docker 容器',
  'docker-buildx': 'Docker 多平台镜像构建插件',
  colima: 'macOS 上的轻量容器运行时（替代 Docker Desktop）',
  lima: 'macOS 上运行 Linux 虚拟机',
  podman: '无守护进程的容器引擎',
  orbstack: 'macOS 上轻快的 Docker 与 Linux 虚拟机',
  kubectl: 'Kubernetes 命令行客户端',
  'kubernetes-cli': 'Kubernetes 命令行客户端（kubectl）',
  helm: 'Kubernetes 应用包管理器',
  k9s: '终端里的 Kubernetes 管理界面',
  minikube: '本地运行 Kubernetes 集群',
  kind: '用 Docker 容器跑本地 Kubernetes 集群',
  terraform: '基础设施即代码工具',
  awscli: 'AWS 官方命令行工具',
  'azure-cli': 'Azure 官方命令行工具',
  'google-cloud-sdk': 'Google Cloud 命令行工具集',
  cloudflared: 'Cloudflare 隧道客户端（内网穿透 / Zero Trust）',
  wrangler: 'Cloudflare Workers 开发部署工具',
  flyctl: 'Fly.io 部署命令行',
  vercel: 'Vercel 部署命令行',
  netlify: 'Netlify 部署命令行',
  'netlify-cli': 'Netlify 部署命令行',
  '@cloudbase/cli': '腾讯云开发 CloudBase 命令行',
  ngrok: '把本地服务暴露到公网的隧道工具',

  // ---------- 数据库 ----------
  mysql: 'MySQL 数据库服务端与客户端',
  'mysql-client': 'MySQL 命令行客户端（不含服务端）',
  postgresql: 'PostgreSQL 数据库',
  libpq: 'PostgreSQL 客户端库与 psql',
  redis: 'Redis 内存数据库',
  sqlite: 'SQLite 嵌入式数据库命令行',
  mongodb: 'MongoDB 文档数据库',
  'mongodb-community': 'MongoDB 文档数据库（社区版）',
  mongosh: 'MongoDB 命令行客户端',
  pgcli: '带自动补全的 PostgreSQL 命令行客户端',
  mycli: '带自动补全的 MySQL 命令行客户端',
  tableplus: '图形化数据库管理客户端',
  dbeaver: '开源的通用数据库图形客户端',
  'dbeaver-community': '开源的通用数据库图形客户端',

  // ---------- 命令行增强 ----------
  ripgrep: '极快的代码文本搜索（rg）',
  fd: '更好用的 find 文件查找',
  fzf: '命令行模糊查找器',
  bat: '带语法高亮的 cat',
  eza: '现代化的 ls 替代品',
  lsd: '带图标与颜色的 ls 替代品',
  zoxide: '记住常用目录的智能 cd',
  jq: '命令行 JSON 处理器',
  yq: '命令行 YAML / JSON / XML 处理器',
  htop: '交互式进程查看器',
  btop: '美观的系统资源监控',
  tmux: '终端复用器（分屏、会话保持）',
  zellij: '现代化的终端复用器',
  starship: '跨 shell 的命令行提示符美化',
  'oh-my-posh': '跨 shell 的命令行提示符美化',
  neovim: '可扩展的 Vim 编辑器',
  vim: '经典终端文本编辑器',
  helix: '内置 LSP 的模态终端编辑器',
  bash: 'Bash shell（比 macOS 自带的新）',
  zsh: 'Z shell',
  fish: '友好的交互式 shell',
  tree: '以树状结构列出目录',
  wget: '命令行下载工具',
  curl: '命令行 HTTP 请求工具',
  httpie: '人性化的命令行 HTTP 客户端',
  xh: '快速的命令行 HTTP 客户端',
  tldr: '简化版命令帮助手册',
  'tlrc': 'tldr 命令帮助手册的 Rust 客户端',
  watch: '定时重复执行命令并显示输出',
  coreutils: 'GNU 核心命令行工具集',
  'gnu-sed': 'GNU 版 sed',
  'gnu-tar': 'GNU 版 tar',
  findutils: 'GNU 版 find / xargs',
  direnv: '按目录自动加载环境变量',
  'the_silver_searcher': '代码搜索工具（ag）',
  hyperfine: '命令行基准测试工具',
  tokei: '统计代码行数',
  cloc: '统计代码行数',
  dust: '直观的磁盘占用查看（du 替代）',
  duf: '直观的磁盘空间查看（df 替代）',
  ncdu: '交互式磁盘占用分析',
  'trash-cli': '命令行把文件移到回收站',
  trash: '命令行把文件移到废纸篓',
  rsync: '增量文件同步工具',
  watchman: '文件变更监听服务（React Native 常用）',
  blueutil: '命令行控制 macOS 蓝牙',
  age: '简单安全的文件加密工具',
  gnupg: 'GPG 加密与签名工具',
  'pinentry-mac': 'macOS 上的 GPG 密码输入框',
  openssl: 'TLS / 加密工具库与命令行',
  'openssl@3': 'TLS / 加密工具库与命令行',
  mkcert: '生成本地受信任的 HTTPS 证书',
  nmap: '网络端口扫描工具',
  mtr: '结合 ping 与 traceroute 的网络诊断',

  // ---------- 媒体与文档处理 ----------
  ffmpeg: '音视频转码与处理工具',
  imagemagick: '命令行图片处理工具',
  'openai-whisper': 'OpenAI Whisper 语音转文字（Python 版）',
  'whisper.cpp': 'Whisper 语音转文字（C++ 高性能版）',
  'whisper-cpp': 'Whisper 语音转文字（C++ 高性能版）',
  tesseract: 'OCR 文字识别引擎',
  'tesseract-lang': 'Tesseract OCR 的多语言识别数据包',
  ghostscript: 'PostScript / PDF 解释与转换工具',
  poppler: 'PDF 渲染库与工具集（pdftotext 等）',
  qpdf: 'PDF 结构变换工具（合并、拆分、加解密）',
  potrace: '把位图描摹成矢量图',
  pandoc: '万能文档格式转换器',
  'yt-dlp': '在线视频下载工具',
  exiftool: '读写图片 / 媒体文件元数据',
  graphviz: '用 DOT 语言画关系图',
  'mermaid-cli': '把 Mermaid 文本渲染成图片',

  // ---------- 移动与 Apple 开发 ----------
  xcodegen: '用 YAML 生成 Xcode 工程文件',
  xcbeautify: '美化 xcodebuild 输出',
  swiftlint: 'Swift 代码规范检查',
  swiftformat: 'Swift 代码格式化',
  fastlane: 'iOS / Android 构建与发布自动化',
  asc: 'App Store Connect 命令行（上架、TestFlight、元数据）',
  axe: 'iOS 模拟器自动化命令行（点击、输入、截图）',
  idb: 'Facebook 的 iOS 设备 / 模拟器调试工具',
  'ios-deploy': '命令行把应用安装到 iOS 真机',
  'android-commandlinetools': 'Android SDK 命令行工具（sdkmanager 等）',
  'android-platform-tools': 'Android 调试工具（adb、fastboot）',
  scrcpy: '在电脑上显示并控制 Android 手机',
  'eas-cli': 'Expo 云构建、提交与 OTA 更新命令行',
  'expo-cli': 'Expo 项目命令行（已被 npx expo 取代）',
  'react-native-cli': 'React Native 命令行',
  flutter: 'Flutter 跨平台应用开发框架',

  // ---------- 前端与 Node 工具 ----------
  '@ant-design/cli': 'Ant Design 组件 API / 示例 / 迁移查询工具',
  typescript: 'TypeScript 编译器',
  'ts-node': '直接运行 TypeScript 的 Node 工具',
  tsx: '直接运行 TypeScript 的 Node 工具（基于 esbuild）',
  pm2: 'Node.js 进程守护与管理器',
  nodemon: '文件变化时自动重启 Node 进程',
  'http-server': '零配置的静态文件服务器',
  serve: '零配置的静态文件服务器',
  prettier: '代码格式化工具',
  eslint: 'JavaScript / TypeScript 代码检查',
  vite: '前端开发服务器与构建工具',
  'create-react-app': 'React 项目脚手架（已不再维护）',
  '@vue/cli': 'Vue 项目脚手架',
  '@angular/cli': 'Angular 项目脚手架',
  'npm-check-updates': '检查并升级 package.json 依赖版本',
  'firebase-tools': 'Firebase 命令行工具',
  lerna: 'JavaScript 多包仓库管理',
  turbo: '多包仓库的高速构建系统',
  nx: '多包仓库的构建与任务编排',
  '@larksuite/cli': '飞书开放平台命令行（文档、消息、多维表格等）',
  '@colbymchenry/codegraph': '代码知识图谱，供 AI Agent 查符号与调用链',
  '@openai/codex': 'OpenAI Codex 编程 Agent 命令行',
  '@anthropic-ai/claude-code': 'Claude Code 编程 Agent 命令行',
  '@google/gemini-cli': 'Google Gemini 编程 Agent 命令行',
  toolbell: '检测本机开发工具更新并推送到群聊（就是本工具）',

  // ---------- AI 与 Agent ----------
  'browser-use': '让 AI Agent 操作浏览器的 Python 库与命令行',
  ollama: '在本地运行开源大模型',
  llm: '在命令行调用各家大模型',
  aider: '终端里的 AI 结对编程工具',
  'codex@openai-codex': '在 Claude Code 里调用 OpenAI Codex 的插件',
  'security-guidance@claude-plugins-official': 'Claude Code 官方安全提示插件（写代码时提示常见漏洞）',
  'security-guidance': 'Claude Code 官方安全提示插件（写代码时提示常见漏洞）',
  superpowers: 'Claude Code 工作流技能合集插件',

  // ---------- macOS 应用（cask） ----------
  betterdisplay: '外接显示器缩放、HiDPI 与亮度调节',
  pearcleaner: '彻底卸载 Mac 应用及残留文件',
  herd: 'Laravel 官方 PHP 本地开发环境',
  'visual-studio-code': '微软的代码编辑器（VS Code）',
  cursor: '内置 AI 的代码编辑器',
  iterm2: 'macOS 终端模拟器',
  warp: '内置 AI 的现代终端',
  ghostty: '快速原生的终端模拟器',
  raycast: '启动器与效率工具（Spotlight 替代）',
  rectangle: '键盘快捷键管理窗口布局',
  postman: 'API 调试与测试工具',
  insomnia: 'API 调试工具',
  'google-chrome': 'Google Chrome 浏览器',
  firefox: 'Firefox 浏览器',
  'docker-desktop': 'Docker 官方桌面版',
  'android-studio': 'Android 官方开发 IDE',
  'sublime-text': '轻快的代码编辑器',
  zed: '高性能协作代码编辑器',
  obsidian: '本地 Markdown 知识库笔记',
  wechatwebdevtools: '微信开发者工具（小程序开发）',
  'wechatwebdevtools-cn': '微信开发者工具（小程序开发）',
};

/** 工具名归一：取 tap 最后一段、去掉 Homebrew 版本后缀（node@22 → node）；scoped npm 包保持原样 */
export function dictKey(name: string): string[] {
  const lower = name.toLowerCase();
  if (lower.startsWith('@')) return [lower];
  const last = lower.split('/').pop() ?? lower;
  const noVer = last.replace(/@[\d.]+$/, '');
  return [...new Set([lower, last, noVer])];
}

export function lookupZh(name: string): string | undefined {
  for (const k of dictKey(name)) {
    const v = DICT_ZH[k];
    if (v) return v;
  }
  return undefined;
}
